import Head from 'next/head'
import { PaginatedComponent } from '@/Components/PaginatedComponent'
export default  function Home({products}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       hiii
       <PaginatedComponent/>
      </main>
    </>
  )
}

export async function getServerSideProps(content){
  const page=content?.query?.page||0;
  const dataToSearch=content?.query?.data||"";
  // console.log(queryData,"queryData...")
  const data=await fetch(`http://localhost:3000/api/blogs?page=${page}&data=${dataToSearch}`)
  const result=await data.json();
  console.log(result,"ooo");


  return{
    props:{
     products:result
    }
  }
}
