import Head from "next/head";
import { PaginatedComponent } from "@/Components/PaginatedComponent";
import { BlogListing } from "@/Components/BlogListing";
import baseUrl from "../Config/baseUrl";
export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BlogListing products={products.result} />
        <PaginatedComponent totalPages={products?.totalPages} />
      </main>
    </>
  );
}

export async function getServerSideProps(content) {
  const page = Number(content?.query?.page) || 1;
  const dataToSearch = content?.query?.data || "";
  const data = await fetch(
    `${baseUrl}/api/blogs?page=${page}&data=${dataToSearch}`
  );
  const res = await data.json();

  return {
    props: {
      products: res,
    },
  };
}
